# General Jekyll Config
highlighter: rouge
url: williamsamtaylor.co.uk
baseurl: '/online-slides'
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
theme: jekyll-theme-minimal